version: '3'
services:
    sonarr:
        image: linuxserver/sonarr
        volumes:
            - /dev/rtc:/dev/rtc:ro
            - ./etc/sonarr:/config
            - ./torrents/series:/tv
            - ./torrents:/downloads
        environment:
            - PUID=1001
            - PGID=1001
        ports:
            - 9002:8989

    transmission:
        image: linuxserver/transmission
        volumes:
            - ./etc/transmission:/config
            - ./torrents:/downloads
            - ./watch:/watch
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe
        ports:
            - 9001:9091
            - 51413:51413
            - 51413:51413/udp

    headphones:
        image: linuxserver/headphones
        volumes:
            - ./etc/headphones:/config
            - ./torrents:/downloads
            - ./torrents/music:/music
        environment:
            - PGID=1001
            - PUID=1001
            - TZ=Europe
        ports:
            - 9000:8181
